import "~/styles/globals.css";

import { type Metadata } from "next";

import localFont from "next/font/local";
import Providers from "./providers";
import ClientLayout from "./client-layout";

export const metadata: Metadata = {
  title: "EFORU",
  description: "Generated by omid bonakdar",
  icons: [{ rel: "icon", url: "/favicon.png" }],
};

const iranSans = localFont({
  src: "./fonts/IRANSansXV.woff2",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html dir="rtl" lang="fa" className={`${iranSans.className} ss02`}>
      <body>
        <Providers>
          <ClientLayout>{children}</ClientLayout>
        </Providers>
      </body>
    </html>
  );
}
